### ISSUE TITLE
Better error handling in the Telemetry module 

### ISSUE THREAD

**Issue by mishanefedov** [a16z/magi#104]
The initialization function in the telemetry module could return an uninformative error message or fail if an error occurred while launching Prometheus Exporter. In particular, if an error occurs while parsing the address string passed to run, the resulting error message will not contain any additional context about the cause of the error. This can make it difficult to debug telemetry issues, especially in production environments

**Comment by merklefruit** [comment]
I will take this!

**Comment by mishanefedov** [comment]
I already created a pull request for this issue
