### ISSUE TITLE
Unable to run on Ubuntu 20.04

### ISSUE THREAD

**Issue by arminghasemazar** [a16z/magi#108]
I've been trying to run Magi on my Ubuntu 20.04. After running `docker compose up -d`, below is the status:

```
[+] Running 5/0
 ✔ Container grafana        Running
 ✔ Container prometheus     Running
 ✔ Container node-exporter  Running
 ✔ Container op-geth        Running
 ✔ Container magi           Started 
```
which clearly shows there is something wrong with container magi. I run `docker logs magi` and below is what I see:
```
error: Found argument '--logs-dir' which wasn't expected, or isn't valid in this context

        If you tried to supply `--logs-dir` as a value rather than a flag, use `-- --logs-dir`

USAGE:
    magi --network <NETWORK> --jwt-secret <JWT_SECRET> --l1-rpc-url <L1_RPC_URL> --l2-rpc-url <L2_RPC_URL> --l2-engine-url <L2_ENGINE_URL> --data-dir <DATA_DIR> --sync-mode <SYNC_MODE>
```

Note that due to some port conflict I had to change ports in docker compose yaml file, which I attach here. 
[magi.txt](https://github.com/a16z/magi/files/11297143/magi.txt)

let me know how I can solve the issue.

**Comment by ncitron** [comment]
Yes apologies for this. We recently added some new command line options but haven't updated the docker images yet. I'll remove those current flags for now as they are optional anyway.

**Comment by arminghasemazar** [comment]
> Yes apologies for this. We recently added some new command line options but haven't updated the docker images yet. I'll remove those current flags for now as they are optional anyway.

Thank you Noah. Would you please ping me when you're done? I can then re-test.

**Comment by ncitron** [comment]
It should be resolved now.
