### ISSUE TITLE
Alchemy api key used for testing fails with error: "Monthly capacity limit exceeded"

### ISSUE THREAD

**Issue by merklefruit** [a16z/magi#114]
While trying to add a test I noticed that every call to the test rpc (with exposed alchemy api key) fails with the error "Monthly capacity limit exceeded". 

https://github.com/a16z/magi/blob/a916e7e875b51d8c70b808304241fa9a44713d58/src/derive/mod.rs#L99

This issue is currently also breaking existing tests because the ChainWatcher test requires to fetch some blocks but it keeps getting stuck for this reason.

Solutions that come to mind:
- use a public rpc url
- use the rpc url loaded from env

**Comment by merklefruit** [comment]
oops, didn't see #94 my bad

**Comment by ncitron** [comment]
Yeah #94 will address. For now I'll just switch it to another key. I don't particularly mind leaking free tier alchemy keys for the time being.
