### ISSUE TITLE
Panic while running Magi locally

### ISSUE THREAD

**Issue by shrimalmadhur** [a16z/magi#123]
I am trying to do local development where I am using docker to setup everything except magi

Updated `.env` looks like
`COMPOSE_PROFILES=metrics,${USE_OP_GETH:+op-geth},${USE_OP_ERIGON:+op-erigon}`

And then I am using `cargo run` with appropriate parameters to run magi. (`l1_rpc_url`, `network`,` jwt-secret`) as params
It is throwing me following error while running 
```
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', src/l1/mod.rs:203:18
```
which is this line in `l1/mod.rs`. 2nd unwrap() in this.
```
let block = l2_provider
                .get_block_with_txs(l2_start_block - 1)
                .await
                .unwrap()
                .unwrap();
```

Everything works while using dockerized containers.
Am I missing something?

**Comment by ncitron** [comment]
So I think what is happening here is somehow op-geth got its state reset. Magi assumes op-geth knows where it left off, and tries to charge ahead, but op-geth doesn't have that block. When we merge #122 this will not be a problem.

In the meantime, you can force your local instance of magi to start from the beginning by deleting the `~/.magi/data` folder. You may also need to delete the op-geth and its associated docker volume by running `make clean` in the root of the magi repo.

Also, if you want a cleaner local dev setup, you can just run `make run-geth` in the repo root and it will create just a op-geth container and none of the monitoring containers without needing to modify those `COMPOSE_PROFILES`.

**Comment by shrimalmadhur** [comment]
That makes sense. Deleting the `~/.magi/data` works. I also see that #122 merged so I will rebase.
