### ISSUE TITLE
Why force https to http in L2 engine url

### ISSUE THREAD

**Issue by GrapeBaBa** [a16z/magi#137]
https://github.com/a16z/magi/blob/ffb6ed11632142fc1ced0fd8f990a6186ba6a24e/src/engine/api.rs#L69-L72

**Comment by ncitron** [comment]
This is a good point, we should probably support both http and https.

Fortunately the engine api is almost always exposed via http. Maybe some infra providers are using https though.

**Comment by GrapeBaBa** [comment]
Got it.
