### ISSUE TITLE
op-erigon backward compatibility issue

### ISSUE THREAD

**Issue by ImTei** [a16z/magi#138]
Hello! I'm Tei from Test in Prod, working on op-erigon.
I want to let you know that there is a breaking change in op-erigon, breaking Magi's docker-compose.

The breaking change is removing `--externalcl` flag, which was a required option until op-erigon `v2.39.0-0.1.1`. 
In subsequent versions, this behavior has been made the default, and using the flag will result in an error.

It seems Magi's [docker-compose](https://github.com/a16z/magi/blob/master/docker/docker-compose.yml#L54) file is using `latest` tag of op-erigon docker image, with an [entrypoint](https://github.com/a16z/magi/blob/master/docker/start-op-erigon.sh#L33) script using `--externalcl`.

So if the docker image of the next release is uploaded, running Magi with op-erigon will be broken.
You should specify the [version](https://hub.docker.com/layers/testinprod/op-erigon/2.38.1-0.1.1-amd64/images/sha256-4da13118f1fd741d948c409c90f3ba75e6371800b8cd237f45fb7ea22f94d591?context=explore) of op-erigon image, or remove `--externalcl` when the next version is released.

The new version will be released in the next few days. You can get the announcement from our discord channel.

Thank you!

**Comment by ncitron** [comment]
Thanks for letting us know! Will removing the flag before the release break the current version?

**Comment by ImTei** [comment]
Yes, it will break the current version(`v2.39.0-0.1.1`).

There are some workarounds:
- Use `--externalcl` and specify the docker image version to `v2.39.0-0.1.1`
- Remove `--externalcl` and add `--networkid=420` flag
  - It will work on both the current version and the next version.
  - `networkid` flag is used for p2p networking.
  -  [`v2.39.0-0.1.1`] If `externalcl` flag is not set and `networkid` is set to 420, erigon will try to launch it's embedded consensus engine but it will failed because the `networkid` is not supported by erigon's consensus engine.

**Comment by ImTei** [comment]
[New version](https://github.com/testinprod-io/op-erigon/releases/tag/v2.43.0-0.1.1) has been released 🙂
