### ISSUE TITLE
Support for Blast? First attempt & errors

### ISSUE THREAD

**Issue by CRossel87a** [a16z/magi#217]
Hi all,

Thanks for this awesome project - I recently noticed it and will work a lot with it. 

Some of you may be interested to see if we can adapt this project to also support Blast. 

I have made the following configuration: https://pastebin.com/78hJAYTU

Then when using the Official Blast RPC as L2:
[Wed, 06 Mar 2024 19:39:50] DEBUG: pooling idle connection for ("https", rpc.blast.io)
[Wed, 06 Mar 2024 19:39:50] DEBUG: Sending request to url: "http://0.0.0.0:8551"
[Wed, 06 Mar 2024 19:39:50] DEBUG: Sending request: Ok("{\"id\":1,\"jsonrpc\":\"2.0\",\"params\":[{\"finalizedBlockHash\":\"0x1abd9791d61f9a55eeecc11b82a0a40771b8c9ce24cf230b8bb29b5839f1bc4a\",\"headBlockHash\":\"0x0470fc5983e29098bb3c7484f9f1b051c9485d3c64285e2519214edf24b870fc\",\"safeBlockHash\":\"0x0470fc5983e29098bb3c7484f9f1b051c9485d3c64285e2519214edf24b870fc\"},{\"gasLimit\":\"0x1c9c380\",\"noTxPool\":true,\"prevRandao\":\"0x205c9f220c3a676f1c1ecfeca572740e4e9e90fdca0640b1ada4addde3740ddb\",\"suggestedFeeRecipient\":\"0x4200000000000000000000000000000000000011\",\"timestamp\":\"0x65e8c219\",\"transactions\":[\"0x7ef90159a0b9e55f76159fecdcdd20f112f9c50cd21317ffa5225877baee67b14aeb6c4cfb94deaddeaddeaddeaddeaddeaddeaddeaddead00019442000000000000000000000000000000000000158080830f424080b90104015d8eb9000000000000000000000000000000000000000000000000000000000127b0020000000000000000000000000000000000000000000000000000000065e8c1c700000000000000000000000000000000000000000000000000000013d44c5580c6e8beaf4c12b839b3b10096d476c21f8de9098a388f2f489cda5a939ce283910000000000000000000000000000000000000000000000000000000000000004000000000000000000000000415c8893d514f9bc5211d36eeda4183226b84aa700000000000000000000000000000000000000000000000000000000000000bc00000000000000000000000000000000000000000000000000000000000a6fe0\",\"0x02f902d483013e31028459682f0084596830358304595f94337827814155ecbf24d20231fca4444f530c055580b90264ac9650d800000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000001a00000000000000000000000000000000000000000000000000000000000000124c04b8d59000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000065e8c44f0000000000000000000000000000000000000000000002024e68388d95c3d0000000000000000000000000000000000000000000000000000021069477680668000000000000000000000000000000000000000000000000000000000000002bae8172a7597b3bf4d3816c76dd8d9b2535262955002710430000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004449404b7c000000000000000000000000000000000000000000000000002106947768066800000000000000000000000022813090d1f36a44218b6f6c000921d8a522ab6d00000000000000000000000000000000000000000000000000000000c001a0cede4ef75bbe23fbd39507aedf7f310960cc3b17057843011c03b601b9d45536a0036ed02269b5cdf586a8ab5979b7f07b858fb30e7c3d9dfa7ec0edf92bdaaaf2\",\"0x02f87883013e3182940f8459682f0085174876e8008262709450ea9f07cfbb6ff2a479e36c70e585306b6933948803bf3b91c95b001280c001a0ee119eb2dbb335ac13b978bb53556b901fe85c4fc40f405bef08fae1540dee39a0073022b65c8def8372f5109d37e532d32dd4c484cd9d66b86a4a19b701abd3da\",\"0xf8ad8266d18310c9ff8302191c945e023c31e1d3dcd08a1b3e8c96f6ef8aa8fcacd180b844535b355c000000000000000000000000d59ca530a5eadf437ba8c626ed8c8512b935270c00000000000000000000000000000000000000000000000000147c8e43dd740083027c86a061e655b24958bb8ff09ed7175ed1f6e1e5857d920867d0d3a4d060c9e4dbbaf7a076a6a8d117b49462adbc739f2f53d2983c62edbd9703896db4747d50a308afe9\"],\"withdrawals\":[]}],\"method\":\"engine_forkchoiceUpdatedV2\"}")
[Wed, 06 Mar 2024 19:39:50] DEBUG: reuse idle connection for ("http", 0.0.0.0:8551)
[Wed, 06 Mar 2024 19:39:50] DEBUG: flushed 3614 bytes
[Wed, 06 Mar 2024 19:39:50] DEBUG: parsed 4 headers
[Wed, 06 Mar 2024 19:39:50] DEBUG: incoming body is content-length (297 bytes)
[Wed, 06 Mar 2024 19:39:50] DEBUG: incoming body completed
[Wed, 06 Mar 2024 19:39:50] DEBUG: pooling idle connection for ("http", 0.0.0.0:8551)
**[Wed, 06 Mar 2024 19:39:50] ERROR: fatal error: Invalid payload attributes**

And then from the op-geth perspective:
ERROR[03-06|19:39:50.481] Failed to create sealing context         err="missing trie node 0837007c871380dba637d29034fdd05389c47598841c98bdd7b773bdee5ecb7d (path ) state 0x0837007c871380dba637d29034fdd05389c47598841c98bdd7b773bdee5ecb7d is not available, not found"
ERROR[03-06|19:39:50.481] Failed to build payload                  err="missing trie node 0837007c871380dba637d29034fdd05389c47598841c98bdd7b773bdee5ecb7d (path ) state 0x0837007c871380dba637d29034fdd05389c47598841c98bdd7b773bdee5ecb7d is not available, not found"
WARN [03-06|19:39:50.482] Served engine_forkchoiceUpdatedV2        conn=127.0.0.1:36892 reqid=1 duration=3.190364ms err="Invalid payload attributes" errdata="{Error:missing trie node 0837007c871380dba637d29034fdd05389c47598841c98bdd7b773bdee5ecb7d (path ) state 0x0837007c871380dba637d29034fdd05389c47598841c98bdd7b773bdee5ecb7d is not available, not found}"

Any thought on these errors if its something we can figure out?

**Comment by merklefruit** [comment]
@CRossel87a Pretty sure Blast is running a modified version of OP stack with closed-source mods, which means it's not possible to run it with Magi right now.

**Comment by ncitron** [comment]
Yeah we are mostly interested in only supporting modifications that are a part of the OP Stack specification (such as the alternate DA spec). Additionally the changes in blast don't seem to be documented well, which would make it hard for us to integrate.

Maybe we can revisit in the future, but closing for now.
