### ISSUE TITLE
Error: Invalid JWT secret key length

### ISSUE THREAD

**Issue by barnabasbusa** [a16z/magi#245]
Hey, I'm trying to run magi in [optimism-package](https://github.com/ethpandaops/optimism-package) and getting jwt secret key length error. 

I'm using the same jwt key length that op-node, op-geth, op-reth and all L1s are using. Could you please explain what length you are expecting? 

```
thread 'main' panicked at src/engine/api.rs:39:54:
called `Result::unwrap()` on an `Err` value: Invalid JWT secret key length.
```

**Comment by alessandromazza98** [comment]
This PR should fix the problem: https://github.com/a16z/magi/pull/246
