### ISSUE TITLE
Long term maintenance plans and production readiness 

### ISSUE THREAD

**Issue by emostov** [a16z/magi#249]
The top level of the readme states:

> Magi is still new, so we expect to find some bugs in the coming months. For critical infrastructure, we recommend using op-node.

I don't see any obvious indication on the long term plans for Magi and the last commit to master branch was a month ago. Considering this, I wanted to clarify:

1) is magi considered production ready? 
2) do the maintainers plan on long term, production grade maintenance for magi?

**Comment by ncitron** [comment]
Yes we do intend to continue to maintain Magi. We have not updated master in a bit but we're working on some upgrades to Magi that gets it to what I would consider production ready. These involve migrating the derivation pipeline to use Optimism's new Kona implementation, which should ensure that any block derived by Magi should match what the Kona prover derives.

**Comment by emostov** [comment]
@ncitron thanks for the quick response! Are you planning any audits on a production release?

**Comment by emostov** [comment]
Also, is there a public roadmap/project tracker anywhere? I am wondering what the best way is for outside contributors to get involved :)

**Comment by ncitron** [comment]
No immediate plans for an audit at the moment but we will probably do an in depth security review at some point. We don't have a great tracker for tasks but if you are interested in contributing feel free to reach out to me on telegram (`@ncitron`)
