### ISSUE TITLE
feat(p2p): Listen to P2P for Unsafe Blocks

### ISSUE THREAD

**Issue by refcell** [a16z/magi#36]
### Overview

Subscribe to P2P Gossip on the configured L2 P2P Network. This will allow us to receive new unsafe blocks from other nodes on the network.

Unsafe chain derivation using p2p block headers. See the [rollup node p2p](https://github.com/ethereum-optimism/optimism/blob/develop/specs/rollup-node-p2p.md)

**Comment by ncitron** [comment]
closed by #127 #129 #133
