### ISSUE TITLE
fix(driver + cli): Graceful restart on Failure

### ISSUE THREAD

**Issue by refcell** [a16z/magi#37]
### Overview

The node should gracefully restart on failure, resuming state.

**Comment by literallymarvellous** [comment]
I'd like to take this on.

Any guidelines on preferred implementation for this?
- will the node restart on any error or specific errors
- what part of the code would the restart functionality be called from?

The driver calls  ```shutdown()``` here on error which I'm guessing we'll have to change
https://github.com/a16z/magi/blob/e70393827e34ab21529bbbde936e7229c30de110/src/driver/mod.rs#L96-L103

**Comment by ncitron** [comment]
Actually, I think for now it is ok if the node stop on failure. A lot of the common failures are handled gracefully such that the core sync loop really only fails during unrecoverable erros.

There is definitely a bigger effort here though to identify more errors that can happen and recovering from them.

Will close this specific issue for now though.
