### ISSUE TITLE
fix: properly decode errors from the engine api

### ISSUE THREAD

**Issue by ncitron** [a16z/magi#88]
Currently if the engine API errors, Magi does not correctly decode it and crashes. We should at the least be able to decode the error and surface it. Maybe we can even start handling some of the ones that are recoverable.

**Comment by xeno097** [comment]
I'd like to work on this issue, any suggestion on how to get this done?

**Comment by ncitron** [comment]
Sounds good! I'd suggest taking a look at the [engine api spec](https://github.com/ethereum/execution-apis/blob/769c53c94c4e487337ad0edea9ee0dce49c79bfa/src/engine/specification.md) to understand how the engine handles errors. From there, and easy way to test that your handling is working it to modify [the api bindings](https://github.com/a16z/magi/blob/master/src/engine/api.rs#L170) to mangle a request and get it to error.
