### ISSUE TITLE
Configure tests to use environment variables for goerli urls, rather than hardcoded urls

### ISSUE THREAD

**Issue by ControlCplusControlV** [a16z/magi#94]
Providers seem to be initialized from a hardcoded url as shown in places like [here](https://github.com/a16z/magi/blob/98bd1abefa91009af9f8b1a708ea09a4f146044b/src/derive/mod.rs#L126). It would be better to refactor this load from a URL such as "GOERLI_RPC," so that it is easy to use a different provider, or even a local one, for testing. I think this approach also leaks an API key 🤔 

Would you be ok with me tackling this @ncitron or @refcell ? I don't have perms to assign myself

**Comment by ControlCplusControlV** [comment]
Just read README, sorry

> In the .env file, modify the L1_RPC_URL field to contain a valid Ethereum RPC. For the Optimism and Base testnets, this must be a Goerli RPC URL. This RPC can either be from a local node, or a provider such as Alchemy or Infura.

So it looks like these tests should instead pull from this already existing environment variable?

**Comment by ncitron** [comment]
Oh yeah that's a good idea. We should probably have it be a different env variable, since once bedrock is on mainnet that one could be a mainnet rpc.

I can assign you to this one. Thanks for pointing this out!
