### ISSUE TITLE
L1 Compatibility

### ISSUE THREAD

**Issue by 0xtimosarkar** [a16z/magi#99]
Hey all 👋🏻

Just came across the project. I have seen the hype on twitter. Awesome work !!!

Just wanted to ask: Do you have the ability to run magi on top of other EVM L1 clients or is currently only op-geth supported?

Its so coincidental to see you guys building another L2 on top of OPstack. :) We are building also on top of OPstack to enable pessimistic rollups @ethereum-pessimism

BR

Timo

**Comment by ncitron** [comment]
Yeah any execution client that has had the optimism modifications should work. We're excited to start testing things out with op-erigon and op-reth when they are ready!

I'll also note that Magi is not an L2, just a client implementation. It works with all OP Stack chains, including Optimism and Base.
